### ISSUE TITLE
Many sensors "Unavailable" After Update to 2.0

### ISSUE THREAD

**Issue by qJake** [alandtse/tesla#183]
## Version of the custom_component

2.0.0 (Previous version was 1.5.0, upgraded from 1.5 straight to 2.0)

Home Assistant Version 2021.12.7

## Describe the bug

Since upgrading to 2.0, many of the sensors are now "Unavailable" for both vehicle and solar data.

My vehicle was "awake", not "sleeping", when this screenshot was taken.

![image](https://user-images.githubusercontent.com/652006/160733673-cb9c1bfd-0214-4e77-96a1-c36dc9147c7f.png)

![image](https://user-images.githubusercontent.com/652006/160733698-d46f43c3-c194-4309-ad8f-eb5318990040.png)

## Error Message (From HA Log)

```text
Logger: homeassistant.components.sensor
Source: custom_components/tesla_custom/tesla_device.py:60
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 7:54:03 PM (1 occurrences)
Last logged: 7:54:03 PM

Error while setting up tesla_custom platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tesla_custom/sensor.py", line 26, in async_setup_entry
    entities.append(TeslaSensor(device, coordinator))
  File "/config/custom_components/tesla_custom/sensor.py", line 35, in __init__
    super().__init__(tesla_device, coordinator)
  File "/config/custom_components/tesla_custom/tesla_device.py", line 60, in __init__
    self.tesla_device.enabled_by_default
AttributeError: 'PowerSensor' object has no attribute 'enabled_by_default'
```

**Comment by alandtse** [comment]
What version of teslasonpy is installed?

**Comment by IvanBrazza** [comment]
I'm having a similar issue, downgrading to 1.7.5 via HACS and all seems to be fine again. Everything shows as unavailable after an unspecified amount of time. If I wake the car up then it all shows up correctly again in HA for a while until the car goes to sleep and eventually it goes back to unavailable.

No errors in the log that I can see when its unavailable.

**Comment by alandtse** [comment]
> I'm running through HACS so I would assume 2.0? But I can double-check it if you cam provide instructions on where I could find out?

You need to get into a console for whatever HA you have.
```
pip list | grep teslajsonpy
```

> No errors in the log that I can see when its unavailable.

Enable logging for teslajsonpy.

**Comment by qJake** [comment]
So, since filing this, I tried the following:

* Updated to 2022.3.8 (no change)
* Removed and re-added the integration with a new refresh token (no change - and my solar panels didn't come back as an entity, they were missing - and the same error in the log as above)
* Downgraded to 1.7.0 and everything is working again

I logged into HA via SSH but `teslajsonpy` is not in `pip list`. I may not have the right SSH terminal - I know there are two (one is a layer up where you can access docker and stuff) and I may be in the wrong one.

Here's the output from SSH, with personal details removed:

```
➜  ~ pip list
Package            Version
------------------ ---------
appdirs            1.4.4
awake              1.0
CacheControl       0.12.10
certifi            2020.12.5
charset-normalizer 2.0.7
colorama           0.4.4
contextlib2        21.6.0
distlib            0.3.3
distro             1.6.0
html5lib           1.1
idna               3.3
lockfile           0.12.2
msgpack            1.0.2
ordered-set        4.0.2
packaging          20.9
pathspec           0.9.0
pep517             0.12.0
pip                20.3.4
progress           1.6
pulsemixer         1.5.1
pyparsing          2.4.7
PyYAML             6.0
requests           2.26.0
retrying           1.3.3
setuptools         52.0.0
six                1.16.0
toml               0.10.2
tomli              1.2.2
urllib3            1.26.7
webencodings       0.5.1
yamllint           1.26.3

➜  ~ ha info
arch: amd64
channel: stable
docker: 20.10.9
features:
- reboot
- shutdown
- services
- network
- hostname
- timedate
- os_agent
- haos
hassos: "7.6"
homeassistant: 2022.3.8
hostname: hassio
logging: info
machine: qemux86-64
operating_system: Home Assistant OS 7.6
state: running
supervisor: 2022.03.5
supported: true
supported_arch:
- amd64
- i386
timezone: █████████

➜  ~ ha core info
arch: amd64
audio_input: None
audio_output: None
boot: true
image: ghcr.io/home-assistant/qemux86-64-homeassistant
ip_address: ████████
last_version: 2022.3.8
machine: qemux86-64
port: ████
ssl: true
update_available: false
version: 2022.3.8
version_latest: 2022.3.8
wait_boot: 600
watchdog: true
➜  ~
```

I have REST API access to my Tesla account and I can grab a JSON payload from the Tesla Owners API for you, if that's what the issue might be. We have vehicles as well as solar panels, and the error seems to stem from loading the solar panel entity.

I can also `pip install teslajsonpy` and run a small self-contained python script on my PC here (and plug in my refresh token or whatever else) if you have a test case / code snippet that I can try. (I don't have a Home Assistant dev environment, but I know Python basics.)

Let me know, thanks! Appreciate the help. 🙂

**Comment by alandtse** [comment]
@ehendrix23 Did we add the `enabled_by_default` to solar entities or was it only vehicles?

**Comment by alandtse** [comment]
Quickes solution may be to catch the AttributeError at https://github.com/alandtse/tesla/blob/dev/custom_components/tesla_custom/tesla_device.py#L59-L61.

**Comment by ehendrix23** [comment]
> @ehendrix23 Did we add the `enabled_by_default` to solar entities or was it only vehicles?

Within teslsjsonpy I added it to VehicleDevice class. Looks like it needs to be added to EnergySiteDevice as well. Submitting PR

**Comment by hawkeye217** [comment]
Same issue with my solar panels after upgrading to 2.0.0.
