### ISSUE TITLE
Unable to install package teslajsonpy==3.12.3 // Home Assistant Core Update 2025.1.2

### ISSUE THREAD

**Issue by sq9fk** [alandtse/tesla#1084]
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### I have read about the Fleet API and understand I may need to use it

- [X] I understand issues relating to read only commands will be auto closed if not using the Fleet API.

### Version of the Tesla component

v3.24.3

### Version of the Tesla car software

2024.45.32.1

### Model

Model 3 Highland

### Current Behavior

After update of Home Assistant, integration was broken. Trying to reinstall but same error occured: 500 Internal Error. When looked at logs:

Registrator: homeassistant.util.package
Source: util/package.py:159

Unable to install package teslajsonpy==3.12.3: error: Failed to fetch: `https://files.pythonhosted.org/packages/3f/8b/dc5fdc3722c5eea0446479bd568d69ec1c91e6bd0bbcd38bf3b21c5e4172/teslajsonpy-3.12.3-py3-none-any.whl.metadata` Caused by: Could not connect, are you offline? Caused by: Request failed after 3 retries Caused by: error sending request for url (https://files.pythonhosted.org/packages/3f/8b/dc5fdc3722c5eea0446479bd568d69ec1c91e6bd0bbcd38bf3b21c5e4172/teslajsonpy-3.12.3-py3-none-any.whl.metadata) Caused by: client error (Connect) Caused by: dns error: failed to lookup address information: Name does not resolve Caused by: failed to lookup address information: Name does not resolve

### Expected Behavior

Update should work.

### Debug logs

```true
Setup failed for custom integration 'tesla_custom': Requirements for tesla_custom not found: ['teslajsonpy==3.12.3'].
```

**Comment by skipishere** [comment]
Can you access that URL from another device on your network? This sounds like an environmental/connection issue rather than an issue with the integration

**Comment by sq9fk** [comment]
hmm DNS working properly on HA and I can access it by copy paste url.

**Comment by sq9fk** [comment]
I see that second guy place post on reddit:
Same story, after upgrade to 2025.1.1 or 1.2 breakse dependency
https://www.reddit.com/r/homeassistant/comments/1hwew0l/202111_breaks_2_custom_integrations/

But behaviour is strange. HA works, dns works in HA and outside, URL works. but for some reason it cannot solve the name or download the dependency.

**Comment by skipishere** [comment]
Not sure what else to suggest, I'm on latest HA, HACS and integration and it all works fine

**Comment by sq9fk** [comment]
Could You do some kind of test: Remove tesla custom integration and try to reinstall it ? Probably there is something with dependencies ?

**Comment by sq9fk** [comment]
It's related to HA (HAOS).

Changed the DNS manualy in HA, restarted and then the integration setup process start.

For others, I've read this thread to find solution:
https://community.home-assistant.io/t/issues-custom-components-and-2024-12-5/814048/10

**Comment by skipishere** [comment]
Sorry just seen your two comments @sq9fk glad you've got a solution. As this was caused by Home Assistant and they have a fix, are you happy if I close this?

**Comment by oagers** [comment]
Hi have the same issue, after reinstalling I get this error: 

Logger: homeassistant.setup
Source: setup.py:334
First occurred: 15:16:05 (1 occurrences)
Last logged: 15:16:05

Setup failed for custom integration 'tesla_custom': Unable to import component: cannot import name 'Controller' from 'teslajsonpy' (/usr/local/lib/python3.13/site-packages/teslajsonpy/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1015, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/tesla_custom/__init__.py", line 29, in <module>
    from teslajsonpy import Controller as TeslaAPI
ImportError: cannot import name 'Controller' from 'teslajsonpy' (/usr/local/lib/python3.13/site-packages/teslajsonpy/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1035, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/tesla_custom/__init__.py", line 29, in <module>
    from teslajsonpy import Controller as TeslaAPI
ImportError: cannot import name 'Controller' from 'teslajsonpy' (/usr/local/lib/python3.13/site-packages/teslajsonpy/__init__.py)

I have 2 more HACS integration that has issue with /usr/local/lib/python3.13/site-packages/%APPLICATION%/__init__.py 
That is NMAP and EASEE Charger

**Comment by skipishere** [comment]
@oagers you seem to have a different issue, please could you open a new issue.
I'm going to close this, as the original issue has been resolved (and wasn't cause by this integration)

**Comment by jammi** [comment]
I got this issue right now, when updating to 2025.2.2

**Comment by skipishere** [comment]
As there hasn't been an update to this I'm going to assume this is (again) an issue with home assistant

**Comment by maniacgt** [comment]
Sorry to resurrect but after an upgrade to 2026.9.1 today this error started for me also. I've reverted to 2026.8.3 for now which works fine.

**Comment by skipishere** [comment]
It would be best to open a new issue given this one is over 2 years old and closed
