### ISSUE TITLE
Integration "failed to set up" after update to 3.19.3

### ISSUE THREAD

**Issue by MrMEScott** [alandtse/tesla#786]
HA 2023.6.3 running in Docker container on an RPi4B.

I updated the custom integration via HACS, to the suggested level, namely 3.19.3

On restart, HA reports the integration "needs attention", and "failed to set up".
Related entities are all "unavailable".

The only mention of the integration in the log is this:
```
ERROR (MainThread) [homeassistant.config_entries] Error setting up entry <tesla_login_id> for tesla_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/__init__.py", line 144, in async_setup_entry
    async_setup_services(hass)
  File "/config/custom_components/tesla_custom/services.py", line 61, in async_setup_services
    hass.services.async_register(
TypeError: ServiceRegistry.async_register() got an unexpected keyword argument 'supports_response'

```
I tried to supply a refresh token via the Integration options interface but it fails saying the id is already registered.

**Comment by alandtse** [comment]
@purcell-lab We probably needed to bump the [hacs.json requirements](https://github.com/alandtse/tesla/blob/dev/hacs.json#L4) when [we added `supports_response` for 3.19.x.](https://github.com/alandtse/tesla/commit/20cc3da52b6c28c8a1172cf0a698e06e5986f48e)

 `Supports_response` was introduced in [HA 2023.07](https://github.com/home-assistant/core/commit/528c2060945ecc8914c54416dbcc2fc35b10f69b).

@MrMEScott Your options are to update HA or downgrade the component.
