### ISSUE TITLE
Issue #998 not fixed on latest version

### ISSUE THREAD

**Issue by MacTh3Mac** [alandtse/tesla#1152]
### Is there an existing issue for this?

- [x] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### Version of the Tesla component

3.25.3

### Version of the Powerwall Gateway software

25.34.1.7e37ef9d

### Model

3

### Current Behavior

Battery % still showing unavailable and generating same errors as were reportedly fixed in #998  #1147 

HAOS 16.2
Core: 2025.10.2

### Expected Behavior

Battery % for Powerwall Shown.

### Debug logs

```true
2025-10-11 17:59:13.323 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 491, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 190, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 571, in _handle_coordinator_update
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1026, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1151, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1088, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1032, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 569, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/sensor.py", line 396, in native_value
    return round(self._energysite.solar_power)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/teslajsonpy/energy.py", line 189, in solar_power
    return self._site_data.get("solar_power")
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

**Comment by Faceless3882** [comment]
> I've just bumped to `3.25.3` which does resolve the percentage. However, it just shows 0kWh for remaining battery. I've had to workaround that by editing `sensor.py` as follows:
> 
> ```
>              return round (self._energysite.percentage_charged*13500/100)
>         """return round(self._energysite.energy_left)"""
> ```
> 
> It's not perfect but better than 0kWh. Not sure if others see the same, [@Faceless3882](https://github.com/Faceless3882)?

Ah yes you're right. I only use the battery % so didn't notice it.

**Comment by ejbatts** [comment]
Battery Remaining sensor not working with PW3 Integration version 3.26

**Comment by MacTh3Mac** [comment]
This issue no longer exists on 3.26 closing issue as any future reports will get compounded with a historical error from several versions ago.

As of 3.26 all sensors appear as they should on PW3 and model Y.  On May 24 2026.

New reports should go to a new issue as will be unrelated to this historical issue.
